plugin:
  has_options: false
  icon: res_file.png

  tools:
    - name: innova_path
      class: icon-road
      icon: icon-road
      is_displayable_in_workspace: true
      is_displayable_in_desktop: false
      
  resources:
    - class: Innova\PathBundle\Entity\Path
      name: path
      is_exportable: false
      icon: res_file.png

    - class: Innova\PathBundle\Entity\Step
      name: step
      is_exportable: false
      icon: res_file.png

    - class: Innova\PathBundle\Entity\NonDigitalResource
      name: non_digital_resource
      is_exportable: false
      icon: res_file.png
