plugin:
  has_options: false
  icon: res_file.png

  tools:
    - name: innova_path
      class: icon-road
      is_displayable_in_workspace: true
      is_displayable_in_desktop: false
      
  resources:
    - class: Innova\PathBundle\Entity\Path
      name: innova_path
      is_exportable: false
      icon: res_file.png
      actions:
          - name: add_favorite
            menu_name: add_favorite

    - class: Innova\PathBundle\Entity\NonDigitalResource
      name: innova_non_digital_resource
      is_exportable: false
      icon: res_file.png
