plugin:
  has_options: false
  icon: res_file.png

  tools:
    - name: innova_path
      class: share-alt
      is_displayable_in_workspace: true
      is_displayable_in_desktop: false
      
  resources:
    - class: Innova\PathBundle\Entity\Path\Path
      name: innova_path
      is_exportable: false
      icon: res_file.png

  widgets:
     - name: innova_path_widget
       is_configurable: false
