parameters: 
    # Controllers
    innova.controller.path.class: Innova\PathBundle\Controller\PathController
    innova.controller.step.class: Innova\PathBundle\Controller\StepController
    innova.controller.path_template.class: Innova\PathBundle\Controller\PathTemplateController
    
    # Managers