services: 
    # Path controller
    innova_path.controller.path:
        class: %innova_path.controller.path.class%
        arguments:
            session:           @session
            router:            @router
            translator:        @translator
            pathManager:       @innova_path.manager.path
            publishingManager: @innova_path.manager.publishing
        scope: request

    # Path template controller
    innova_path.controller.path_template:
        class: %innova_path.controller.path_template.class%
        arguments:
            formFactory:         @form.factory
            pathTemplateManager: @innova_path.manager.path_template
            pathTemplateHandler: @innova_path.form.handler.path_template
        scope: request
        
    # Player controller
    innova_path.controller.path_player:
        class: %innova_path.controller.path_player.class%
        arguments:
            router:      @router
            session:     @session
            stepManager: @innova_path.manager.step
        calls:
          - [setRequest, [@request]]
        scope: request
          
    # Editor controller
    innova_path.controller.path_editor:
        class: %innova_path.controller.path_editor.class%
        arguments:
            objectManager:   @doctrine.orm.entity_manager
            router:          @router
            formFactory:     @form.factory
            resourceManager: @claroline.manager.resource_manager
            pathManager:     @innova_path.manager.path
            pathHandler:     @innova_path.form.handler.path
        scope: request
