services: 
    # Path controller
    innova_path.controller.path:
        class: %innova_path.controller.path.class%
        arguments:
            session:            @session
            router:             @router
            translator:         @translator
            pathManager:        @innova_path.manager.path
            publishingManager:  @innova_path.manager.publishing
        
    # Path template controller
    innova_path.controller.path_template:
        class: %innova_path.controller.path_template.class%
        arguments:
            formFactory:         @form.factory
            pathTemplateManager: @innova_path.manager.path_template
            pathTemplateHandler: @innova_path.form.handler.path_template
        scope: request
        
    # Player controller
    innova_path.controller.path_player:
        class: %innova_path.controller.path_player.class%
        arguments:
            router:      @router
            session:     @session
            stepManager: @innova_path.manager.step
        calls:
          - [setRequest, [@request]]
        scope: request

    # Contextual Editor controller
    innova_path.controller.path_contextual_editor:
        class: %innova_path.controller.contextual_editor.class%
        calls:
          - [setContainer, ["@service_container"]]
        arguments:
            securityContext: @security.context
            router:      @router
            formFactory: @form.factory
            session:     @session
            translator:  @translator
            stepHandler: @innova_path.form.handler.step
        scope: request
          
    # Editor controller
    innova_path.controller.path_editor:
        class: %innova_path.controller.path_editor.class%
        arguments:
            objectManager:   @doctrine.orm.entity_manager
            router:          @router
            formFactory:     @form.factory
            session:         @session
            translator:      @translator
            pathHandler:     @innova_path.form.handler.path
            pathManager:     @innova_path.manager.path
            resourceManager: @claroline.manager.resource_manager
        scope: request