services: 
    # Path controller
    innova_path.controller.path:
        class: %innova_path.controller.path.class%
        arguments:
            session:            @session
            router:             @router
            translator:         @translator
            pathManager:        @innova_path.manager.path
            publishmentManager: @innova_path.manager.publishment
        
    # Step controller
    innova_path.controller.step:
        class: %innova_path.controller.step.class%
        arguments:
            kernelRoot:      %kernel.root_dir%
            entityManager:   @doctrine.orm.entity_manager
            securityContext: @security.context
            stepManager:     @innova_path.manager.step
        
    # Path template controller
    innova_path.controller.path_template:
        class: %innova_path.controller.path_template.class%
        arguments:
            formFactory:         @form.factory
            pathTemplateManager: @innova_path.manager.path_template
            pathTemplateHandler: @innova_path.form.handler.path_template
        scope: request
        
    # Player controller
    innova_path.controller.path_player:
        class: %innova_path.controller.path_player.class%
        calls:
          - [setContainer, ["@service_container"]]
          
    # Editor controller
    innova_path.controller.path_editor:
        class: %innova_path.controller.path_editor.class%
        arguments:
            router:      @router
            formFactory: @form.factory
            session:     @session
            translator:  @translator
            pathHandler: @innova_path.form.handler.path
        scope: request