services: 
    # Path controller
    innova_path.controller.path:
        class: %innova_path.controller.path.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager
            session:         @session
            securityContext: @security.context
            router:          @router
            translator:      @translator
            pathManager:     @innova_path.manager.path
        calls:
          - [setRequest, ["@?request="]]
        scope: request
        
    # Step controller
    innova_path.controller.step:
        class: %innova_path.controller.step.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager
            securityContext: @security.context
            stepManager:     @innova_path.manager.step
        calls:
          - [setRequest, ["@?request="]]
        scope: request
        
    # Path template controller
    innova_path.controller.path_template:
        class: %innova_path.controller.path_template.class%
        arguments:
            entityManager:       @doctrine.orm.entity_manager
            pathTemplateManager: @innova_path.manager.path_template
        calls:
          - [setRequest, ["@?request="]]
        scope: request
        
    # Player controller
    innova_path.controller.path_player:
        class: %innova_path.controller.path_player.class%
        calls:
          - [setContainer, ["@service_container"]]