services: 
    innova.path.controller:
        class: %innova.controller.path.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager
            session:         @session
            securityContext: @security.context
            router:          @router
            translator:      @translator
            pathManager:     @innova.manager.path_manager
        calls:
          - [setRequest, ["@?request="]]
        scope: request
        
    innova.step.controller:
        class: %innova.controller.step.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager
            securityContext: @security.context
            stepManager:     @innova.manager.step_manager
        calls:
          - [setRequest, ["@?request="]]
        scope: request