services:
    # Path type
    innova_path.form.type.path:
        class: %innova_path.form.type.path.class%
        tags:
          - { name: form.type, alias: innova_path }
          
    # Path handler
    innova_path.form.handler.path:
        class: %innova_path.form.handler.path.class%
        arguments:
            pathManager: @innova_path.manager.path
        calls:
            - [setRequest, [@request]]
        scope: request

    # NonDigitalResource type
    innova_path.form.type.non_digital_resource:
        class: %innova_path.form.type.non_digital_resource.class%
        tags:
          - { name: form.type, alias: innova_non_digital_resource }

    # NonDigitalResource handler
    innova_path.form.handler.non_digital_resource:
        class: %innova_path.form.handler.non_digital_resource.class%
        arguments:
            pathManager: @innova_path.manager.non_digital_resource
        calls:
            - [setRequest, [@request]]
        scope: request

    # Step type
    innova_path.form.type.step:
        class: %innova_path.form.type.step.class%
        tags:
          - { name: form.type, alias: innova_step }


     # Step handler
    innova_path.form.handler.step:
        class: %innova_path.form.handler.step.class%
        arguments:
            stepManager: @innova_path.manager.step
        calls:
            - [setRequest, [@request]]
        scope: request