services:
    # Abstract Path type
    innova_path.form.type.abstract_path: 
        abstract: true
        class: %innova_path.form.type.abstract_path.class%
    
    # Path type
    innova_path.form.type.path:
        class:  %innova_path.form.type.path.class%
        parent: innova_path.form.type.abstract_path
        tags:
          - { name: form.type, alias: innova_path }
          
    # Path template type
    innova_path.form.type.path_template:
        class:  %innova_path.form.type.path_template.class%
        parent: innova_path.form.type.abstract_path
        tags:
          - { name: form.type, alias: innova_path_template }