services: 
    # AbstractPath handler
    innova_path.form.handler.abstract:
        abstract: true
        class: %innova_path.form.handler.abstract.class%
        calls:
            - [setRequest, [@request]]

    # Path handler
    innova_path.form.handler.path:
        class: %innova_path.form.handler.path.class%
        parent: innova_path.form.handler.abstract
        arguments: [@innova_path.manager.path]
        scope: request

    # PathTemplate handler
    innova_path.form.handler.path_template:
        class: %innova_path.form.handler.path_template.class%
        parent: innova_path.form.handler.abstract
        arguments: [@innova_path.manager.path_template]
        scope: request
