services:
    # Path type
    innova_path.form.type.path:
        class: %innova_path.form.type.path.class%
        tags:
          - { name: form.type, alias: innova_path }
          
    # Path handler
    innova_path.form.handler.path:
        class: %innova_path.form.handler.path.class%
        arguments:
            pathManager: @innova_path.manager.path
        calls:
            - [setRequest, [@request]]
        scope: request