services:
    innova_path.listener.path:
        class: %innova_path.listener.path.class%
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: open_innova_path,         method: onOpen }
            - { name: kernel.event_listener, event: create_form_innova_path,  method: onCreateForm }
            - { name: kernel.event_listener, event: create_innova_path,       method: onCreate }
            - { name: kernel.event_listener, event: delete_innova_path,       method: onDelete }
            - { name: kernel.event_listener, event: copy_innova_path,         method: onCopy }
            - { name: kernel.event_listener, event: administrate_innova_path, method: onAdministrate }
            - { name: kernel.event_listener, event: manageresults_innova_path, method: onManageresults }
    innova_path.listener.notification_listener:
        class: %innova_path.listener.notification.class%
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_notification_item_resource-innova_path-step_unlock, method: onCreateNotificationItem }
            - { name: kernel.event_listener, event: create_notification_item_resource-innova_path-step_unlockdone, method: onCreateNotificationUnlockDone }