services:
  innova.listener.path_tool:
    class: Innova\PathBundle\Listener\ToolListener
    calls:
      - [setContainer, ["@service_container"]]
    tags:
      - { name: kernel.event_listener, event: open_tool_workspace_innova_path, method: onWorkspaceOpen }

  innova.listener.path:
    class: Innova\PathBundle\Listener\Resource\PathListener
    calls:
      - [setContainer, ["@service_container"]]
    tags:
      - { name: kernel.event_listener, event: open_innova_path, method: onPathOpen }
      - { name: kernel.event_listener, event: create_form_innova_path, method: onPathCreateForm }
      - { name: kernel.event_listener, event: create_innova_path, method: onPathCreate }
      - { name: kernel.event_listener, event: delete_innova_path, method: onPathDelete }
      - { name: kernel.event_listener, event: copy_innova_path, method: onPathCopy }