services:
    # Path manager
    innova_path.manager.path:
        class: %innova_path.manager.path.class%
        arguments:
            objectManager:             @doctrine.orm.entity_manager
            securityContext:           @security.context
            resourceManager:           @claroline.manager.resource_manager
            nonDigitalResourceManager: @innova_path.manager.non_digital_resource
            stepManager:               @innova_path.manager.step
        calls:
            - [setRequest, ["@?request="]]
        scope: request

    # NonDigitalResource manager
    innova_path.manager.non_digital_resource:
        class: %innova_path.manager.non_digital_resource.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager
            securityContext: @security.context
            resourceManager: @claroline.manager.resource_manager

    # Path template manager
    innova_path.manager.path_template:
        class: %innova_path.manager.path_template.class%
        arguments:
            entityManager: @doctrine.orm.entity_manager
        calls:
            - [setRequest, ["@?request="]]
        scope: request

    # Step manager
    innova_path.manager.step: 
        class: %innova_path.manager.step.class%
        arguments: 
            om: @doctrine.orm.entity_manager